### ISSUE TITLE
Broken link to code

### ISSUE THREAD

**Issue by lukerm** [pzzhang/VinVL#2]
The link to "Scene Graph Benchmark Repo" on [this page](https://github.com/pzzhang/VinVL/blob/main/DOWNLOAD.md) is broken. Crucially, this is the one that contains the code to get the image-region features. 

Could you update it so that it's possible to run the code? 

Thanks,
Luke

**Comment by valuefish** [comment]
Same issue. Looking forward to the "Scene Graph Benchmark Repo" code.

**Comment by pzzhang** [comment]
@lukerm  @valuefish  The Scene Graph Benchmark Repo is released.
