### ISSUE TITLE
Where can I find "train_vgoi6_clipped.yaml" and "test_vgoi6_clipped.yaml"?

### ISSUE THREAD

**Issue by zdxdsw** [pzzhang/VinVL#21]
Hello! Thank you so much for providing the well-structured code!

I'm trying to extract image regions features by `python tools/test_sg_net.py --config-file sgg_configs/vgattr/vinvl_x152c4.yaml TEST.IMS_PER_BATCH 2 MODEL.WEIGHT models/vinvl/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 DATA_DIR "../maskrcnn-benchmark-1/datasets1" TEST.IGNORE_BOX_REGRESSION True MODEL.ATTRIBUTE_ON True`, but I can't find the download links for two config files specified in vinvl_x152c4.yaml, namely **TRAIN: ("visualgenome/train_vgoi6_clipped.yaml",)** and **TEST: ("visualgenome/test_vgoi6_clipped.yaml",)**

What I could find were these two TRAIN: ("visualgenome/train_danfeiX_relation_nm.yaml",), TEST: ("visualgenome/test_danfeiX_relation.yaml",) after downloading visualgenome by `path/to/azcopy copy 'https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/datasets/visualgenome' <target folder> --recursive`. However, with these two config files, my program would complain `KeyError: 'box_features'`, which seemed to be caused by the returned prediction not including the 'box_features' field. 

Any suggestions?
Thanks a lot!

**Comment by zdxdsw** [comment]
I see. I have to set TEST.OUTPUT_FEATURE to True in the yaml file.

**Comment by gsrivas4** [comment]
@zdxdsw I am getting same error `KeyError: 'box_features'`, even when I set TEST.OUTPUT_FEATURE to True in the yaml file and also pass `TEST.OUTPUT_FEATURE True` as a command line parameter. Below is the command that I am running. 
```
python tools/test_sg_net.py --config-file sgg_configs/vgattr/vinvl_x152c4_edited.yaml TEST.IMS_PER_BATCH 2 MODEL.WEIGHT pretrained_model/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 DATA_DIR datasets TEST.IGNORE_BOX_REGRESSION True MODEL.ATTRIBUTE_ON True TEST.OUTPUT_FEATURE True
```

Did you have to just set any other parameter to resolve the error? I have checked the value of `output` variable here - https://github.com/microsoft/scene_graph_benchmark/blob/main/maskrcnn_benchmark/engine/inference.py#L38 when passing a batch of images as input. Seems output has only BoxList object and there are no feature outputs. 

Any debugging pointers will be really helpful.

**Comment by sangwoo0123** [comment]
> @zdxdsw I am getting same error `KeyError: 'box_features'`, even when I set TEST.OUTPUT_FEATURE to True in the yaml file and also pass `TEST.OUTPUT_FEATURE True` as a command line parameter. Below is the command that I am running.
> 
> ```
> python tools/test_sg_net.py --config-file sgg_configs/vgattr/vinvl_x152c4_edited.yaml TEST.IMS_PER_BATCH 2 MODEL.WEIGHT pretrained_model/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 DATA_DIR datasets TEST.IGNORE_BOX_REGRESSION True MODEL.ATTRIBUTE_ON True TEST.OUTPUT_FEATURE True
> ```
> 
> Did you have to just set any other parameter to resolve the error? I have checked the value of `output` variable here - https://github.com/microsoft/scene_graph_benchmark/blob/main/maskrcnn_benchmark/engine/inference.py#L38 when passing a batch of images as input. Seems output has only BoxList object and there are no feature outputs.
> 
> I have explained about my issue in more details here - [microsoft/scene_graph_benchmark#24 (comment)](https://github.com/microsoft/scene_graph_benchmark/issues/24#issuecomment-892897376).
> 
> Any debugging pointers will be really helpful.

Also having the same issue... Can someone please help out?

**Comment by gsrivas4** [comment]
@zdxdsw I could actually resolve the issue. It was something from my side. I feel setting  TEST.OUTPUT_FEATURE to True should be work.

**Comment by codeandproduce** [comment]
Having followed the steps above, I'm still getting the 'box-features' error even with TEST.OUTPUT_FEATURE=True.

**Comment by codeandproduce** [comment]
Here's a potential solution for those struggling with the above issue still:

https://github.com/microsoft/scene_graph_benchmark/issues/39#issuecomment-894746184

**Comment by KatieGou** [comment]
Hi, I wonder how can you set TEST.OUTPUT_FEATURE to True in the yaml file? It seems sgg_configs/vgattr/vinvl_x152c4.yaml [https://github.com/microsoft/scene_graph_benchmark/blob/main/sgg_configs/vgattr/vinvl_x152c4.yaml](url) doesn't have any argument OUTPUT_FEATURE.

**Comment by sarvghotra** [comment]
@zdxdsw would it be possible to share the LABELMAP_FILE (visualgenome/VG-SGG-dicts-vgoi6-clipped.json) if you have it lying around? All the download links on the repo are broken and the authors are not responsive either. TIA!

PS: I am a PhD student at Mila working on a paper that needs results from this work.
