### ISSUE TITLE
Getting error when downloading VinVL pretrained model and 

### ISSUE THREAD

**Issue by gsrivas4** [pzzhang/VinVL#8]
Thank you for providing the code for VinVL. I am getting similar error when I try to download the models given here - https://github.com/pzzhang/VinVL/blob/main/DOWNLOAD.md#pre-trained-models
```
azcopy copy https://penzhanwu2.blob.core.windows.net/results/vinvl/od_models/vinvl_vg_x152c4.pth .
INFO: Scanning...

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
```
I am getting similar error when I try to download the `associated labelmap` at this link https://penzhanwu2.blob.core.windows.net/results/vinvl/od_models/VG-SGG-dicts-vgoi6-clipped.json. However, I do not get the link when I try to download the features from this link - https://biglmdiag.blob.core.windows.net/vinvl/image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000/. 
Let me know how can I resolve this issue.

**Comment by gsrivas4** [comment]
Seems the download links have been updated and the download is passing the new links:

* https://penzhanwu2.blob.core.windows.net/results/vinvl/od_models/vinvl_vg_x152c4.pth to https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth
* https://penzhanwu2.blob.core.windows.net/results/vinvl/od_models/VG-SGG-dicts-vgoi6-clipped.json to https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/VG-SGG-dicts-vgoi6-clipped.json

Downloading from the link https://biglmdiag.blob.core.windows.net/vinvl/image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000/ works.

**Comment by YilinGeStudy** [comment]
使用了https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth，下载结果是：
INFO: Scanning...
INFO: Autologin not specified.

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
